language: clojure
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
env:
  global:
    - PGPORT=5433
    - DB=postgresql://app_user:please01@localhost:5433/money_test
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main
  - sleep 1
before_script:
  - createdb -e money_test
  - psql -c "CREATE USER app_user SUPERUSER PASSWORD 'please01';" -U postgres
script:
  - lein with-profile test migrate
  - lein with-profile test partition 2015-01-01 2017-12-31
  - lein test
