---
name: clj-money
volumes:
  sql-data-17:
services:
  sql:
    image: postgres:17
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - sql-data-17:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: please03
      POSTGRES_USER: admin_user
      POSTGRES_DB: admin_user
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=please03 sh -c 'pg_isready -U admin_user -d admin_user'"]
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: please01
    ports:
      - 16543:80
    depends_on:
      - sql
