services:
  web:
    image: clj-money-web:latest
    ports:
      - 3010:3000
    environment:
      CLASSPATH: /opt/clj-money/config:/opt/clj-money/clj-money.jar
    volumes:
      - ./env/docker:/opt/clj-money/config:ro
