#!/bin/bash

if [ ! -d ./lib ]; then
  mkdir ./lib
fi

URL=https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
curl $URL --location > ./lib/opentelemetry-javaagent.jar
