alter table accounts
  drop constraint fk_accounts_entity,
  drop constraint fk_accounts_account;
alter table attachments
  drop constraint fk_attachments_transaction,
  drop constraint fk_attachments_image;
alter table budget_items
  drop constraint fk_budget_items_budget,
  drop constraint fk_budget_items_account;
alter table budgets
  drop constraint fk_budgets_entity;
alter table commodities
  drop constraint fk_commodities_entity;
alter table entities
  drop constraint fk_entities_user;
alter table images
  drop constraint fk_images_user;
alter table imports
  drop constraint fk_imports_image;
alter table lots_transactions
  drop constraint fk_lots_transactions_transaction,
  drop constraint fk_lots_transactions_lot;
alter table lots
  drop constraint fk_lots_commodity,
  drop constraint fk_lots_account;
alter table prices
  drop constraint fk_prices_commodity;
alter table reconciliations
  drop constraint fk_reconciliations_account;
alter table transactions
  drop constraint fk_transactions_entity;
alter table transaction_items
  drop constraint fk_transaction_items_transaction,
  drop constraint fk_transaction_items_account,
  drop constraint fk_transaction_items_reconciliation;
