ALTER TABLE lot_items ALTER COLUMN price TYPE NUMERIC(12, 4);
ALTER TABLE lot_items ALTER COLUMN shares TYPE NUMERIC(10, 4);

ALTER TABLE lots ALTER COLUMN shares_purchased TYPE NUMERIC(10, 4);
ALTER TABLE lots ALTER COLUMN shares_owned TYPE NUMERIC(10, 4);
ALTER TABLE lots ALTER COLUMN purchase_price TYPE NUMERIC(12, 4);

ALTER TABLE prices ALTER COLUMN price TYPE NUMERIC(12, 4);

ALTER TABLE cached_prices ALTER COLUMN price TYPE NUMERIC(12, 4);

ALTER TABLE reconciliations ALTER COLUMN balance TYPE NUMERIC(12, 4);

ALTER TABLE scheduled_transaction_items ALTER COLUMN quantity TYPE NUMERIC(12, 4);

ALTER TABLE transaction_items ALTER COLUMN quantity TYPE NUMERIC(12, 4);
ALTER TABLE transaction_items ALTER COLUMN value TYPE NUMERIC(12, 4);
ALTER TABLE transaction_items ALTER COLUMN balance TYPE NUMERIC(12, 4);

ALTER TABLE transactions ALTER COLUMN value TYPE NUMERIC(12, 4);

ALTER TABLE accounts ALTER COLUMN quantity TYPE NUMERIC(12, 4);
ALTER TABLE accounts ALTER COLUMN value TYPE NUMERIC(12, 4);

ALTER TABLE budget_items ALTER COLUMN periods TYPE NUMERIC(12, 4)[];
