name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: please01
          POSTGRES_USER: app_user
          POSTGRES_DB: money_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: 2.11.1
          clj-kondo: 2023.12.15
      - name: Install dependencies
        run: lein deps
      - name: Lint with clj-kondo
        uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src:test
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ClojureScript tests
        run: lein fig:test
      - name: Run database migrations
        run: lein with-profile +test migrate
      - name: Create database partitions
        run: lein with-profile +test partition 2015-01-01 2017-12-31
      - name: Run tests
        run: lein test
