name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: please01
          POSTGRES_USER: app_user
          POSTGRES_DB: money_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: lein deps
      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.04.05'
      - name: Run linter
        run: clj-kondo --lint src:test --dependencies
      - name: Run database migrations
        run: lein with-profile +test migrate
      - name: Create database partitions
        run: lein with-profile +test partition 2015-01-01 2017-12-31
      - name: Run tests
        run: lein test
